import yaml
import pyperclip3

from ec_map_types import ErrorCode, FunctionErrorMap, ClassErrorMap

from ec_map_fcakefile import fcakefile
from ec_map_fcakedir import fcakedir

def gen_func_map_str(fmap: FunctionErrorMap) -> str:
    result = f'### {fmap.func_name}\n\n'
    result += '|Error Code|Associated Policy|Context|\n'
    result += '|:---------|:----------------|:------|\n'
    for err in fmap.error_codes:
        policy_str = err.linked_policy if err.has_policy() else 'None'
        result += f'|{err.code_value}|{policy_str}|{str(err.extra_context)}|\n'

    return result

def err_map_to_markdown(cls: ClassErrorMap) -> str:
    result = ''
    result += f'## {cls.typename}\n'
    result += f'The following section details the possible error codes generated by **{cls.typename}**.'
    for func in cls.func_map:
        result += '\n\n'
        result += gen_func_map_str(func)
    result += '\n\n'
    return result

maps = [
    fcakefile,
    fcakedir
]
map_str = ''

map_str = '\n\n'.join(err_map_to_markdown(m) for m in maps)

pyperclip3.copy(map_str)
print ('Copied to clipboard.')